application.base.url: https://elenco-oiv.performance.gov.it/
repository.base.url: http://alfresco-community.test.si.cnr.it/alfresco/
org.apache.chemistry.opencmis.binding.spi.type: browser

user.admin.password: admin
server.servlet.context-path: /
siper.sedi.url: http://localhost:8080/rest/static/json/sedi.json
helpdesk:
  url: https://helpdesk-coll.ecaasdfp.cloudspc.it/rest
  ucat:
    url:
  istanza: /HDTrasparenza
  password: PdtAdmin

mail.smtp.socketFactory.fallback: false
hazelcast:
  port:
    autoincrement: false
rrd:
  path: remote-shared,remote-fp
  skipmd5: true

ipa:
  url:
    base: https://www.indicepa.gov.it/public-services/opendata-read-service.php
    amministrazioni: ${ipa.url.base}?dstype=FS&filename=amministrazioni.txt

flows:
  enable: false
  resource: http://demoscrivaniadigitale.si.cnr.it
  token: ${flows.resource}/oauth/token
  authorize: ${flows.resource}/oauth/authorize
  taskComplete: ${flows.resource}/api/tasks/complete
  processInstance: ${flows.resource}/api/processInstances
  currentTask: ${flows.processInstance}/currentTask
  processDefinitionId: iscrizione-elenco-oiv:1:4
  username: app.elenco-oiv
  password: app.elenco-oiv
  clientId: sprintapp
  clientSecret: my-secret-token-to-change-in-production