spring.application.name: jconon

hazelcast.members: 127.0.0.1

server.context-path: /jconon

ajp:
  port: 8009
  timeout: 120000

org.apache.chemistry.opencmis.binding.clientcompression: false
org.apache.chemistry.opencmis.binding.compression: true

#Tomcat
server.tomcat.basedir: ./
server.tomcat.access-log-enabled: true
server.tomcat.access-log-pattern: '%h %l %u %t "%r" %s %b %D'

shell.auth.simple.user.name: ${user.admin.username}
shell.auth.simple.user.password: ${user.admin.password}