repository.base.url: http://alfresco-community.test.si.cnr.it/alfresco/
user.admin.password: admin
rrd.path: remote-shared,remote-fp
server.context-path: /
mail.from.default: performance@governo.it
siper.sedi.url: http://localhost:8080/rest/static/json/sedi.json