repository.base.url: http://alf4fp.cedrc.cnr.it:8080/alfresco/
user.admin.password: Alf4FpPw
rrd.path: remote-shared,remote-fp
server.context-path: /
mail.from.default: performance@governo.it
siper.sedi.url: http://localhost:8080/rest/static/json/sedi.json